services:
    zypher:
        container_name: zypher
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/zypher
        working_dir: /zypher
        command: [ "tail", "-f", "/dev/null" ]
        tty: true
        stdin_open: true
